### ISSUE TITLE
clean up the repository

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/CommunityRepairCafe#15]
@Math-TECH-Hub → can we check what we can clean up a bit in this Repo after merging #14 ?

- [x] do we need the picture?
- [x] can we have all files in Markdown .md format?
- [x] proper file naming can be improved a bit?
- [x] anything else?

**Comment by timmwille** [comment]
@PyGamma @gibertgibs @chardso anything to add?

**Comment by gibertgibs** [comment]
Will share my comment soon...just have to re-pass through the project.

**Comment by timmwille** [comment]
@gibertgibs :+1:

**Comment by chardso** [comment]
I think it will not change the direction of the activities, do or don't.

**Comment by timmwille** [comment]
I guess we can go for this one? @gibertgibs also to solve #17
