### ISSUE TITLE
What teams do we have for the first Run? [16th Feb]

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/CommunityRepairCafe#16]
Juba1+2, Adjumani, Pagarinya, Eden, Bor?

**Comment by gibertgibs** [comment]
As in what exactly do you mean?

**Comment by chardso** [comment]
I could go for platform Africa first and follows by YEF.

**Comment by timmwille** [comment]
@gibertgibs @chardso → I was referring to Teams on a locality based scenario, will give an introduction tomorrow
We will have our first big collective Project Planning ahead of us, combining the features of Repositories and the power of GitHub Project Management:
https://github.com/orgs/ASKnet-Open-Training/projects/1

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/104253593-285ca880-5475-11eb-8fc6-714623fb4df5.png)

**Comment by timmwille** [comment]
@dawaedina27 maybe we can list all possible team combinations and discuss them here first?

**Comment by dawaedina27** [comment]
@timmwille  are all the members of Track II going to work on this repository (repair cafe) am abit confused

**Comment by dawaedina27** [comment]
I know teams like #PA Team (Ocea), #YEF (Adjumani), #Gogirls (Juba), and #Bor team.

 Please members let's keep on listing the teams that are missing in my list😊

**Comment by dawaedina27** [comment]
PA Team members 
@romeoplat , @mawarose , @Math-TECH-Hub, @dawaedina27 and (@maliarich ?)

**Comment by mawarose** [comment]
Great team

**Comment by dawaedina27** [comment]
GoGirls Team members 
@Nunas455, @B-yine, @yyenki, @yaievy .............

**Comment by dawaedina27** [comment]
YEF Team members 
@chardso, @gibertgibs

**Comment by timmwille** [comment]
ATAKA Team members 
@wunbaai @yarmanyang

**Comment by timmwille** [comment]
For YEF we also have @PyGamma and for junubOS we have @babyomer who needs at least one more member

So I suggest to have max 3 members per team → they can add external volunteer experts to their team but the whole Idea for Track II is to practice Open Collaboration in the Online scenario combined with offline activity

**Comment by timmwille** [comment]
@acii4u where would you like to participate ? :)

**Comment by chardso** [comment]
It could better if specialists move from team to team,as in if we have platform Africa doing it ,yet team joins vise versa but not across boarders,and SOPs be observed.

**Comment by maliarich** [comment]
A go-girls participant could join @babyomer, and it could be little bit balance.

**Comment by maliarich** [comment]
Platform Africa  seems to be complete based on the original plan of 3 members per a team .
JOS @babyomer and @sunday767 (+ one invited repair )
Go-girls  @B-yine ,@nunas and Rana.
YEF .@chadso + gilbert + Gama 
Ataka . @yarmanyang and @wunbaai +( one invited repair )

**Comment by chardso** [comment]
Here,I think the decision doesn't belong to a single member,and I think we shall have to meet or communicate as members of a particular team and pass out the resolution as soon as possible.

**Comment by babyomer** [comment]
I have one of student that I train ,  defiantly she will join my team , if
my idea is OK to u timm and malimungu.

**Comment by timmwille** [comment]
sure @babyomer → it is absolutely ok to find extra collaborators on the ground for your team, just you as members of Track II are in charge of sharing your concepts and documentation on GitHub :)

By the way, @maliarich in this case the mentors and trainers are counted as fully collaborators as well (as for me I will also set up a little team for helping remotely)
@romeoplat @yyenki @PyGamma @maliarich 
all of us will be needed to make this a success, also for coordination with the hubs, as they are at least the host or facilitators of this event (so listen to their requirements and forms to fill etc. → is part of the challenge to combine the offline and the online collaboration).

**Comment by timmwille** [comment]
> It could better if specialists move from team to team,as in if we have platform Africa doing it ,yet team joins vise versa but not across boarders,and SOPs be observed.

@chardso we will be "moving" online from team to team → each team can think about what plattform to use for communication and tackeling the problems → I would suggest to create an issue for each device? but also using a telegram group is not a bad idea → though the documentation work later might be harder
the BBB Channel I will create will have diffrent break-out channels one can join, one for each team and will stay open in parallel to the events happening. But for exchanging chat and pictures, even small recordings etc. also to be used for the documentation later on I would recommend another online collaboration tool → each team should have a computer and a smartphone at hand.

FYI @maliarich @yyenki @romeoplat @PyGamma → we might want to talk about this as well in the upcoming weeks :)

**Comment by timmwille** [comment]
do we have an overview of the teams yet? I think very team should create an issue for themselfs in here:
https://github.com/ASKnet-Open-Training/CommunityRepairCafe/issues

@maliarich can give you a hand if you need help

I'll add a checklist to the description soon, based on what we have worked out so far

Also take a look at the Guides (specifically the Open Documentation Guide has a Repair Café example, but not fully applicable as for planning and informing Community etc. is missing), but also the Open Training Guide might hold valuable aspects of Event Planning checks https://openculture.agency/open-education-resources/

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/105869582-aaada680-5ff7-11eb-9fcc-2f1a3f75883f.png)

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/105869919-0bd57a00-5ff8-11eb-82c8-8d078d1f8b11.png)

**Comment by timmwille** [comment]
#18 and #19 and #23 

where is the rest @maliarich @PyGamma ?

**Comment by chardso** [comment]
Am yet to be informed whether @PyGamma will be in adjumani team or Pagerinya.

**Comment by timmwille** [comment]
> Am yet to be informed whether @PyGamma will be in adjumani team or Pagerinya.

today we have decided, together with @gibertgibs and @PyGamma that Pagirinya team will have their event later in march so @PyGamma is a free man for adjumani team :D

**Comment by timmwille** [comment]
@maliarich I need help providing a sheet with all the teams, I think #23 #18 #19 are lamost good to go and the team members are clear now. for #24 we will see for the date, probably the 23rd of March as finals are over then, and have a bit of time for planning.

for the team in #25 we'll also check for alternative date, 16th might be too tight in schedule now. For the Juba team I was hoping to have at least one team ready for the 16th of Feb but @yaievy @B-yine @Nunas455 @sunday767 or @rana-najm might update me on this one. Else we have another event on 23rd of March with all SSD teams and Pagirinya Team? what you think @romeoplat @PyGamma @yyenki @maliarich ?

**Comment by chardso** [comment]
Adjumani or Pagerinya?
