### ISSUE TITLE
Don't we think time frame should be added to this activity? Reason,much relactancy.

### ISSUE THREAD

**Issue by chardso** [ASKnet-Open-Training/CommunityRepairCafe#21]

**Comment by maliarich** [comment]
I think the time frame could help in planning too. Thumbs up .

**Comment by timmwille** [comment]
yes added it to the project management → check this out https://github.com/orgs/ASKnet-Open-Training/projects/1

**Comment by timmwille** [comment]
So is it a time frame for the event itself?

**Comment by chardso** [comment]
We close these,it was written when people were slow with feedbacks on telegram.
