### ISSUE TITLE
How the online remote repair cafe will happen.

### ISSUE THREAD

**Issue by chardso** [ASKnet-Open-Training/CommunityRepairCafe#22]

**Comment by timmwille** [comment]
so you want a checklist in best case? just for Tools and Materials or even for the Event itself?

@maliarich @vugawilliam maybe you can also help answer this?

I would go like this:

- Make a list of what you need minimum
- Make a wishlist to add more if there is budget
- design everything with a box/bag as a kit concept
- draft space/concept on how the event will happen
- communicate with your partner organisation/hub ASAP
- check the budget with admins (associated hubs, trainers)

**Comment by chardso** [comment]
How the event will happen?
1. At the reception we shall an expert to register the broken devices brought by the community,that's table one.
2 . our experts will be specialised,one will hand solars and radios,the second will handle small electronics such as phones,lighting systems etc.
3 . the third one will handle computer repair and maintainance(both mechanical and soft ware).
4 . fixing of the devices will start after establishing the registered number of devices at the reception.
5 .A support team in which one personnel will have a camera or a smart phone to take the coverage of the activities ie photos,video clips etc.
6 .One person will be doing online documentations such the people away from the site will follow online proceedings and comment where necessary.
7 .Before the everything resumes we shall have an expert who will introduce the set up to our online teams.
8 .One of the expert to interview a community member about how the repair cafe has impacted him/her.
9.comments by teams involved, @ member to write about the activities
10 .Closing remarks by the host.

**Comment by timmwille** [comment]
> How the event will happen?
> 
>     1. At the reception we shall an expert to register the broken devices brought by the community,that's table one.
>        2 . our experts will be specialised,one will hand solars and radios,the second will handle small electronics such as phones,lighting systems etc.
>        3 . the third one will handle computer repair and maintainance(both mechanical and soft ware).
>        4 . fixing of the devices will start after establishing the registered number of devices at the reception.

can you add those points here @chardso ? I think this matter is solved in general?
https://github.com/ASKnet-Open-Training/CommunityRepairCafe/issues/2
