### ISSUE TITLE
How to attract the community to your repair cafe?

### ISSUE THREAD

**Issue by dawaedina27** [ASKnet-Open-Training/CommunityRepairCafe#3]

**Comment by PyGamma** [comment]
This is nice tasks to be undertaken because we can have a nice repair cafe but if we do not have approach to attract people to our activities, it basically becomes dormant.

**Comment by Math-TECH-Hub** [comment]
Provision of better quality services such as good customer care, Not charging alot of money from the people.

**Comment by PyGamma** [comment]
Thanks Mathew for considering to work on this issues however, when you are working on an issue you will have to create a file in the repository that has the issue and then provide your solution in that file then commit the changes, when the solution answers the issues very well, the issue creater will then close the issue. So this is what you are suppose to do so far, first create a file in this repository and then move this answers you provided as issues comment to that file, besides you can add more points.

**Comment by chardso** [comment]
To my own understanding, community repair cafes,are free of charge,the communities pay for only spares where need arises.

**Comment by chardso** [comment]
First of all the repair cafe is for free,meaning devices that can be fixed without aspare are handled.
  And those that require a spare,its a task of the device owner to buy a spare and the team fixes for  free,all these will attract the communities
 However the gesture of welcoming the community members to this will spice it up.
    The most meaningful one is doing it together with them will expose them to easy problem identification in devices and in the near future ,they can handle them personally.

**Comment by timmwille** [comment]
I think now is a good moment while you wait on my feedback for the budget to continue with Ideas on this one and get it started?
Shall we include a guide to the files/repo?

**Comment by chardso** [comment]
Yeah,its so vital for future references.

**Comment by timmwille** [comment]
@vugawilliam may you add the measures you took, today it sounded your strategy worked pretty well :D  
- Radio announcement?
- Telling friends and Family?
- Adding other ads? Or just telling everyone "free repairs"?

→ I think it is crucial that the original idea of a repair café is not only to repair devices but also to include the community in the process so they might learn themselves on what to do next time it breaks.

**Comment by chardso** [comment]
Radio announcement could the fastest way to deliver the message to the community since time is not by our side.

**Comment by vugawilliam** [comment]
This is going to be the remixes of massages, could be on radio or peer to peer massage, all can work at the moment, so any can work
