### ISSUE TITLE
Juba GoGirls ICT Remote Repair cafe [6/7th March]

### ISSUE THREAD

**Issue by maliarich** [ASKnet-Open-Training/CommunityRepairCafe#34]
@Nunas455  @B-yine  @sunday767 
When you're done with the concept stuff feel free to use this issue. :)

**Comment by yyenki** [comment]
## Remote Mobile Repair Café
**Location:** Gudele II and Hai Commercial (St Thomas and Juba Day secondary school)
**Target:** Two secondary schools and their community.
**Date:** 6th – 7th March 2021
**Duration**: 10:00am – 4:00pm
## Objectives
•	To build the capacity of the teachers on hand practices by repairing their only devices.
•	To support the teachers by repairing their devices to keep preparing the learning materials to the students.
•	To document using Github and have open tool Collaboration with other participants in track II remotely using Telegram, social media online streaming during the two days.
## Description:
 The outbreak of the COVID-19, with a lot of restriction affected schools; schools must plan for other alternative ways to deliver lessons to keep students learning at home. However, many schools and the teachers face challenges of their devices like computers, phones and speakers have broken down and the cost of fixing these devices are expensive thus, many can’t afford.
 GoGirls ICT Initiative South Sudan will organize a repair café in Juba that will span for two days to support two schools that are also beneficiaries of its other activities and their surrounding communities with their electric devices that need to be fixed. 
## Budget for the two days event
1. **Tools and Materials** -  Notebooks,   Sticky Notes, Flip Charts, Pens, Markers, Extension Cables, Sole tape, Soldering paste
**Cost**  - $250
2.Catering -  Including drinking water, lunch during the repair locations.
**Cost**  - $200
3.**Local transport**-  Transport for the team which includes the hiring of a car.
**Cost**  - $200
4.**Expert fees** -  Person who will provide technical support to the team.
**Cost**  - $ 250
5. **Documentation** - During the event, streaming online on all the social media.
**Cost**  - $ 50
6. **Airtime** -  Mobilization of the team and participants.
**Cost**  - $ 50
7 **.Sanitize and Face Mask** for the team and participants during the events to keep sanitizing their hands.
**Cost**  - $ 50
**Grand Total**:  1,050 USD

## Evaluation

**Outcomes  & Indicators**

**Initial Stage** 
 1.There is not any repair offer to schools   to assess and repair their devices to support them in preparing their  learning materials for students.
**Target** 
Teachers and their communities know how   to assess their electronic devices issues 
**Activity**
 Github and telegram documentation

**Initial Stage** 
2.Teachers and their communities have no knowledge about repairing their electronic devices
**Target** 
Teachers and their communities   have basic knowledge about repairing their electronic devices.
**Activity**
Assessing and repairing devices.

## Outputs 
**Initial Stage** 
1. No documentation of Local Electronic issues
**Target** 
Documentation of Local issues on electronic devices and how they can be fixed
**Activity**
 Online documentation of this issues.

**Initial Stage** 
  2.  No step by step guide on how to fix electronic device issues 
**Target**
 A guide on fixing electronic issues which can be used by the   community 
**Activity**
 A step by step guide of fixing basic electronic device issues.

**Comment by yyenki** [comment]
@timmwille, I was thinking if the dates we have selected are not syncing according to plan, then we can have the event on 23rd March as already decided and I will only have to change the date according.

**Comment by timmwille** [comment]
@yyenki @Nunas455 @B-yine @sunday767 

I must say I love the school approach, so definitely we shall try to make it happen.

Some general things to consider first:
1. The Idea of the remote Community Repair Café is to have multiple events (in best case not just from one organisation) in different locations and connect online to collaborate on challenges and share live the documentation and impression around the event
2. Together with the teams in Juba junubOS #33 and Bor #25 as well as Adjumani #23 it would be best find ways to collaborate at the same date I think team Adjumani #23 is ready to go, so could work
3. The budget is split in 3 Positions: 1) Tool-Kit (will be an Addon ot the ASKriot/ASKotec) 2) Materials (Wire, solder, diodes etc.) and 3) Event costs (Equipment, renting, power, space, refreshments, logistics, fees, flipcharts etc.)


---

**Comment by timmwille** [comment]
Ok on the Budget: 

a) split for the Repair Kit in 2 positions: around 200$ Tools and 50$ Materials (it can also differ a bit, just with a list of planned items to get and good reasoning we might be flexible, especially for materials as this is session costs)
b) It looks like the sum of things listed above is 800$ for event costs and easy to handle as you plan to be in 2 locations at once we might even be flexible if e.g. more airtime is needed, just secure the online collaboration can happen
c) is in documentation also Github and Telegram included? (please not just use facebook :D) 

---

I would like to get a rough concept regarding the content of the repair kit, you can also get some inspiration from the other teams #24 #19 #18 #23 that have it ready

**Comment by timmwille** [comment]
## Team Juba (GoGirls)
[GitHub](https://github.com/ASKnet-Open-Training/CommunityRepairCafe/issues/34)


| Budget | total | comment |
| -------- | -------- | -------- |
| **Tools***     | 762000UGX /= 210,-USD     | make sure to have a working kit  |
| **Materials***     | 50,-USD     | for two locations you might need to add more?     |
| **Event**     | 800$     | good to go     |
- [x] \* Tools and Materials good to go 
- [x] Event costs

**Comment by chardso** [comment]
I would support having the same date to share challenges online during the repair.

**Comment by yyenki** [comment]
> Ok on the Budget:
> 
> a) split for the Repair Kit in 2 positions: around 200$ Tools and 50$ Materials (it can also differ a bit, just with a list of planned items to get and good reasoning we might be flexible, especially for materials as this is session costs)
> b) It looks like the sum of things listed above is 800$ for event costs and easy to handle as you plan to be in 2 locations at once we might even be flexible if e.g. more airtime is needed, just secure the online collaboration can happen
> c) is in documentation also Github and Telegram included? (please not just use facebook :D)
> 
> I would like to get a rough concept regarding the content of the repair kit, you can also get some inspiration from the other teams #24 #19 #18 #23 that have it ready

**Comment by yyenki** [comment]
1. @timmwille We are not renting the space that's why we are collaborating with these schools. 
2. For the issue of power, we are still waiting for feedback from the schools if they will provide us with power or we need to buy fuel to run their school generators.
3. Github and telegram documentation is included.
4. @sunday767,  Yes, the tool kit is an add-on to what we have in our #ASKriot. @sunday767 did an assessment of the tools and materials based on the devices we want to repair before we worked on our budget though let's wait for her feedback as she was to assess the market again.
5. Any of the teams are really free to join us during this event.

**Comment by chardso** [comment]
Waiting to join online.

**Comment by timmwille** [comment]
good, keep in mind to do some repair Setup and event documentation here:
https://github.com/ASKnet-Open-Training/Minimal-Repair-Setup/issues/7

**Comment by timmwille** [comment]
@yyenki can you add your comment here?

**Comment by timmwille** [comment]
Quote via @yyenki 

> @timmwille, I received the below feedback from the repair cafe team. They shared with me some adjustments to the budget based on their assessment yesterday and who will be part of their team for the two days and added an extra $350.
> Materials - Extra $50
> Documentation extra $150 for hiring someone to take professional pictures for the two days.
> Experts Extra $150.
> This implies that our budget for Tools and Materials will be $300, documentation will be $ 200 for including and personnel will be $400 as fees for four experts who will join @B-yine @Nunas455 and @sunday767.
> This makes the overall budget to be at $1400 for the two days event.

**Comment by timmwille** [comment]
@yyenki please help me understand: 

1. what extra materials? I still have little understanding of what exactly you're planning to buy, so what is it based on?
2. Documentation is a meant as a fee? seems quite a lot for a few pictures, will this also produce a video and proper publication/storytelling later? → a report?
3. Experts: sure a good Idea, but what kind of expertise? As far as I see it, for @B-yine @sunday767 @Nunas455 the event is a hands on practice to asure the online collaboration (very little so far, so can be a good chance to change that, I trust in them to do this properly) 
4. As @sunday767 was to join #33 Team of junubOS is what I understood → what has changed?

→ don't get me wrong, I think if 2 Events and 2 days are planned (also needs 2teams?) I think we might be able to find some extra budget, but I could not see the proper arguments to proof it necessary yet. 

So if you could help me understand, would be good though the event is tomorrow we have to find other ways maybe. (this comment got lost in the wrong issue)
