### ISSUE TITLE
restructure README and extract other info in separate file

### ISSUE THREAD

**Issue by timmwille** [ASKnet-Open-Training/CommunityRepairCafe#5]
Quote @PyGamma 

>Hey team, this is really great work however, I recommend that the read me file should be used for describing the repository only not for scripting the entire content of the project or activities idea. So please create a file and move most of the details you have provided here and leave only the description of the repository in the read me file. Doing this as soon as possible will give us the opportunity to move forward.

**Comment by gibertgibs** [comment]
Okay perhaps, I will pull request to work things out....

**Comment by chardso** [comment]
Hey,I felt the file I added on the readme was not rhyming,so i removed it.

**Comment by timmwille** [comment]
oh, so I might have messed things up by pulling the changes from @Math-TECH-Hub in :( @gibertgibs

**Comment by timmwille** [comment]
but can you check again, might be ok

**Comment by bmen** [comment]
created pull request for this #13

**Comment by timmwille** [comment]
Nice, guess this is solved
